name: test

on: [push, pull_request]

env:
  CAIRO_COMPILER_VERSION: 1.0.0-alpha.2

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget https://github.com/starkware-libs/cairo/releases/download/v$CAIRO_COMPILER_VERSION/cairo-lang-$CAIRO_COMPILER_VERSION-x86_64-unknown-linux-musl.tar.gz
          tar -xvf cairo-lang-0.1.0-x86_64-unknown-linux-musl.tar.gz
          export PATH=$PATH:$(pwd)/cairo/bin
          make build

  run:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget https://github.com/starkware-libs/cairo/releases/download/v$CAIRO_COMPILER_VERSION/cairo-lang-$CAIRO_COMPILER_VERSION-x86_64-unknown-linux-musl.tar.gz
          tar -xvf cairo-lang-0.1.0-x86_64-unknown-linux-musl.tar.gz
          export PATH=$PATH:$(pwd)/cairo/bin
          # TODO: uncomment when demo is ready
          #make run

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget https://github.com/starkware-libs/cairo/releases/download/v$CAIRO_COMPILER_VERSION/cairo-lang-$CAIRO_COMPILER_VERSION-x86_64-unknown-linux-musl.tar.gz
          tar -xvf cairo-lang-0.1.0-x86_64-unknown-linux-musl.tar.gz
          export PATH=$PATH:$(pwd)/cairo/bin
          make test
