name: test

on: [push, pull_request]

env:
  CAIRO_COMPILER_VERSION: 1.0.0-alpha.2
  # Temporary use artifacts from custom CI build
  RELEASE_ARCHIVE_LINK: https://github.com/starkware-libs/cairo/suites/10618265874/artifacts/529772830
  RELEASE_ARCHIVE_NAME: release-x86_64-unknown-linux-musl.zip
  #RELEASE_ARCHIVE_LINK: https://github.com/starkware-libs/cairo/releases/download/v1.0.0-alpha.2/cairo-lang-1.0.0-alpha.2-x86_64-unknown-linux-musl.tar.gz
  #RELEASE_ARCHIVE_NAME: cairo-lang-1.0.0-alpha.2-x86_64-unknown-linux-musl.tar.gz

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget $RELEASE_ARCHIVE_LINK
          tar -xvf $RELEASE_ARCHIVE_NAME
          export PATH=$PATH:$(pwd)/cairo/bin
          make build

  run:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget $RELEASE_ARCHIVE_LINK
          tar -xvf $RELEASE_ARCHIVE_NAME
          export PATH=$PATH:$(pwd)/cairo/bin
          # TODO: uncomment when demo is ready
          #make run

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget $RELEASE_ARCHIVE_LINK
          tar -xvf $RELEASE_ARCHIVE_NAME
          export PATH=$PATH:$(pwd)/cairo/bin
          make test
